name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --baseURL https://tchinchow.github.io/story-customized/ --config exampleSite/config.toml --contentDir exampleSite/content --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          keep_files: false
          enable_jekyll: false
          # user_name: <username>
          # user_email: <username@email.com>
          # external_repository: <username>/<username>.github.io
          publish_dir: ./public
          publish_branch: gh-pages
        #   cname: example.com